id: P005632
initial_creation_type: ocr
source_metadata:
  id: bdr:W21863
  title: ཤེས་རབ་རྒན་པོའི་འབེལ་གཏམ
  author: ''
  volumes:
    7b734a9f17fc4687b6a5423682adeb98:
      image_group_id: I5685
      title: ''
      volume_number: 1
      total_pages: 239
