id: P005632
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 12:08:25.500534
source_metadata:
  id: bdr:W21863
  title: ཤེས་རབ་རྒན་པོའི་འབེལ་གཏམ
  author: ''
  volumes:
    7b734a9f17fc4687b6a5423682adeb98:
      image_group_id: I5685
      title: ''
      volume_number: 1
      total_pages: 239
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
